{% set name = "lckr_jupyterlab_variableinspector" %}
{% set version = "3.2.2" %}

package:
  name: jupyterlab-variableinspector
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c53cdf80460706a01a129759854f15390bde077d4e77481b87e3eef4f8ce13de

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab =4
    - pip
    - python >=3.8,<4.0
  run:
    - python >=3.8
    - jupyterlab >=3.0.0

test:
  requires:
    - jupyterlab =4
    - pip
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@lckr/jupyterlab_variableinspector.*OK.*(python, lckr_jupyterlab_variableinspector)"

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-variableInspector
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Variable Inspector extension for Jupyterlab.

extra:
  recipe-maintainers:
    - fcollonval
